import Head from "next/head";
import styles from "../styles/Home.module.css";
import "bootstrap/dist/css/bootstrap.min.css";

import Carousel from "../comps/carousel";
import Unauthorized from "./Unauthorized";
import { useSession } from "next-auth/client";

export default function Home() {
  const [session, loading] = useSession();
  var content = (
    <div className={styles.container}>
      <Head>
        <title>MediaTracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome, {session?.user?.name}</h1>

        <Carousel />
      </main>
    </div>
  );
  return session ? content : <Unauthorized></Unauthorized>;
}
