import Head from "next/head";

import Carousel from "../components/carousel";
import Unauthorized from "./Unauthorized";
import { useSession } from "next-auth/client";

export default function Home() {
  const [session, loading] = useSession();
  if (session) {
    console.log(session);
    return (
      <div>
        <Head>
          <title>MediaTracker</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className="bg-primary-dark h-full overflow-auto">
          <h1 className="text-white font-bold text-2xl m-4">
            Welcome, {session?.user?.name}
          </h1>
          <h2 className="ml-4 text-white font-semibold text-xl">
            Recently Watched...
          </h2>
          <Carousel />
          <h2 className="ml-4 text-white mt-2 font-semibold text-xl">
            Your List...
          </h2>
          <Carousel />
        </main>
      </div>
    );
  }
  if (loading) {
    return <div className="m-4 text-white">Loading...</div>;
  }
  return <Unauthorized></Unauthorized>;
}
