import Head from "next/head";
import styles from "../styles/Home.module.css";

import Carousel from "../comps/carousel";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>MediaTracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to MediaTracker</h1>
        <Carousel />
      </main>
    </div>
  );
}
